language: java

jdk:
  - oraclejdk8

addons:
  sonarqube:
    organization: sonarqubegeekshubs
    token:
      secure: "F00VrK67q8V2a+3AoJXXv+OWxJE/PQCI0eocNR4wK0UqQ2OpNavLRA30re8YjMYfVdSiYA6s4DEMGcEHMWCAHFNg3HL0x/bo7lJ9Kk8mbjoQeHwTtGNuHPjcgLNcG911wJz3XpYRelS9rV/5pOEi9mIMs4aqnZwSxe+oPD4ZSuHSHFQ1kIaGeVTqJN26kTT10fKoMbP0moUY2pEt8QlUfWDVK+xOvLWcr0xLBF/bS/pk0dyOjfW8/SQRbt9qhF0VOv1rxbDFOFCDiriezKpD0AnnhLr/gwlTrnbTSo09ajDSmO8Lf0Kmd+o48HcJwechxw7HjwaDKs7j0kIeQdu6W4XJfrKsz8IlGThb3Q8gaDcC2+cG5V4glhW4hFQhZ7o7VXMb/Nu1D9hQqRdMvCV0Y1DnG37rQT0t6ODP7O0rw6Ce4th0ZB0m+1LqK6+PJaurFCxtPJVXPTIT8+QXZM1bheJ6j+ESl5Te8MtrCl+xjwedL/PwFS8Qso5vhT1UPFhyp5QIpWmmHkd2/Et034r+fzG0Ri97H1ucn+3TORHkpvMaHD6oOFI5Vbr92kVIFN00bn+WJbo4461ohZVU90LwicMkZmd1Nkvnq837Lri6qn9yzWLBRCcvBLsqKtRlsXW1mNzB0defquQqkDaLEp8AygzBadcsCBbXPMXkDFkux+s="
    github_token:
      secure: "z2qkZNsAp1ZAyhJr8EBQ2IyOsIf/nRdcIY/PL3OeLP5k1vCmyYNOxSYKaSFY+IJV3LfwdlUwj+/Q0PaZzZRzQ+v/joYmhhKF+LWQi40Ht4Qxq3rWdZEaG7U5NqOq7hwKDtTu2LiKVHTY9HADUYkDOn3GEFcL9ZKD/DoYVbGgDabRF37i5ohsEeaUmnBMAVMyUDsHJo12llt1TXbYrvLSXjzLqn6TXG6gCSTJyF3Js8B24mhkwoMX28ikMN+qDncAXRN97Grp/4PDz3+oUuJAycPkMF0aQ0ZnWztivWQkvqG9Vn9tFwlMKXwLST92e10wdmdfh6UcCs90eXlrAR4SraEuopsqc9uRRUsbzWKw5cvUVT2yvFG8eI7d8UFG/vLLcTSZYBpj/ygBXUNMuWByKVm3NtfY7znbkI4A0GYnBlE7+c1YyC7N7qrwSOmCKQz7PDzyfBHIkVi4tKYqfTdiQENMqnzw14vSspfTkzr73CUoh2xp+awpbBM3bl48Fu/sB5XU3CsC7xQmvMvIIExGj6XMwdC3CNoyucMxqNdJO4XeZcePxpGIJjTeJjehoLrqWlW3CJMnR53Rn5CKbL8n9F19QnVQygKMK18DrNgTBmhs9k+0OxFZof4gEDECJ7fvA0ItIlP6P5G+hrYlqmmrnRH1QRekLaNUh2UtN8OwfTA="
    branches:
      - .*

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -f java-custom-rules/pom.xml

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

notifications:
  email: false
